// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCom3-Quf-5gmkLcBYvchNhqcpvebarbGo',
    appId: '1:443943307854:web:8e376404687c87b363111f',
    messagingSenderId: '443943307854',
    projectId: 'elsa-task',
    authDomain: 'elsa-task.firebaseapp.com',
    storageBucket: 'elsa-task.firebasestorage.app',
    measurementId: 'G-1M8FKZN6ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Swnzsuz9ZSWWlncZnJaGWjgrk4NoVcw',
    appId: '1:443943307854:android:efe3b96a5265b65263111f',
    messagingSenderId: '443943307854',
    projectId: 'elsa-task',
    storageBucket: 'elsa-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCct6VioNyJfMV4PzrtRYqnfb_McpWoPyA',
    appId: '1:443943307854:ios:ef669af207dfea9e63111f',
    messagingSenderId: '443943307854',
    projectId: 'elsa-task',
    storageBucket: 'elsa-task.firebasestorage.app',
    iosBundleId: 'com.example.elssaTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCct6VioNyJfMV4PzrtRYqnfb_McpWoPyA',
    appId: '1:443943307854:ios:ef669af207dfea9e63111f',
    messagingSenderId: '443943307854',
    projectId: 'elsa-task',
    storageBucket: 'elsa-task.firebasestorage.app',
    iosBundleId: 'com.example.elssaTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCom3-Quf-5gmkLcBYvchNhqcpvebarbGo',
    appId: '1:443943307854:web:793df9448393ca9e63111f',
    messagingSenderId: '443943307854',
    projectId: 'elsa-task',
    authDomain: 'elsa-task.firebaseapp.com',
    storageBucket: 'elsa-task.firebasestorage.app',
    measurementId: 'G-TDPS0LNB4E',
  );
}
